# Proyecto X - SQLeros

### Se crea ésta notebook en Colab
Incidencia BBT2-11

### Se clona repositorio de Alkemy (BBVA-BDS-W1-T2)

Incidencia BBT2-5

In [1]:
!git clone https://github.com/alkemyTech/BBVA-BDS-W1-T2.git

Cloning into 'BBVA-BDS-W1-T2'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 32 (delta 6), reused 0 (delta 0), pack-reused 17
Receiving objects: 100% (32/32), 75.32 MiB | 31.70 MiB/s, done.
Resolving deltas: 100% (7/7), done.

### Se crea rama de trabajo individual (GIT)

Incidencia BBT2-8

# Sección SQLite

Importación SQL + Pandas

In [2]:
#Importamos SQlite
import sqlite3
#Importamos pandas
import pandas as pd

### Crear una base de datos de SQLite

Incidencia BBT2-14

In [3]:
# Conectar a la base de datos
conn = sqlite3.connect('ecommerce.db')
cursor = conn.cursor()

## Creación de Dataframes de pandas con asignación de rutas

In [4]:
#Creación de Dataframes de pandas con asignación de rutas
ecommerce_customers = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_customers_dataset.csv')
ecommerce_geolocation=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_geolocation_dataset.csv')
ecommerce_order_items=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_items_dataset.csv')
ecommerce_order_payments=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_payments_dataset.csv')
ecommerce_order_reviews=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_reviews_dataset.csv')
ecommerce_orders=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_orders_dataset.csv')
ecommerce_products = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_products_dataset.csv')
ecommerce_sellers=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_sellers_dataset.csv')
ecommerce_product_category_name_translation=pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de product_category_name_translation.csv')

### Mostramos en lista las columnas de cada DF por visibilidad

In [5]:

ecommerce_customers.columns.tolist()

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [6]:
ecommerce_orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [8]:
ecommerce_order_payments.columns.tolist()

['order_id',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value']

In [9]:
ecommerce_geolocation.columns.tolist()

['geolocation_zip_code_prefix',
 'geolocation_lat',
 'geolocation_lng',
 'geolocation_city',
 'geolocation_state']

In [18]:
ecommerce_order_reviews.columns.tolist()

['review_id',
 'order_id',
 'review_score',
 'review_comment_title',
 'review_comment_message',
 'review_creation_date',
 'review_answer_timestamp']

## Guardamos los DF como tablas en la BD

In [10]:
# Guardar los df como tablas en la base de datos ecommerce.db
ecommerce_customers.to_sql('customers', conn, if_exists='replace', index=False)
ecommerce_order_items.to_sql('order_items', conn, if_exists='replace', index=False)
ecommerce_order_payments.to_sql('order_payments', conn, if_exists='replace', index=False)
ecommerce_orders.to_sql('orders', conn, if_exists='replace', index=False)
ecommerce_products.to_sql('products', conn, if_exists='replace', index=False)
ecommerce_geolocation.to_sql('geolocation', conn, if_exists='replace', index=False)
ecommerce_order_reviews.to_sql('reviews', conn, if_exists='replace', index=False)
ecommerce_sellers.to_sql('sellers', conn, if_exists='replace', index=False)
ecommerce_product_category_name_translation.to_sql('product_category_name_translation', conn, if_exists='replace', index=False)

71

## Extracción de datos desde las tablas orders y payments

Incidencia BBT2-19

In [11]:
# Crear un DataFrame que contenga el JOIN de la tabla orders y tabla payments.
orders_and_payments = pd.read_sql_query('''
SELECT * FROM orders o
INNER JOIN order_payments op
ON o.order_id = op.order_id''', conn)

In [12]:
orders_and_payments

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,e481f51cbdc54678b7cc49136f2d6af7,1,credit_card,1,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,e481f51cbdc54678b7cc49136f2d6af7,2,voucher,1,18.59
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,e481f51cbdc54678b7cc49136f2d6af7,3,voucher,1,2.00
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,53cdb2fc8bc7dce0b6741e2150273451,1,boleto,1,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,47770eb9100c2d0c44946d9cf07ec65d,1,credit_card,3,179.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103881,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,9c5dedf39a927c1b2549525ed64a053c,1,credit_card,3,85.08
103882,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,63943bddc261676b46f01ca7ac2f7bd8,1,credit_card,3,195.00
103883,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,83c1379a015df1e13d02aae0204711ab,1,credit_card,5,271.01
103884,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,11c177c8e97725db2631073c19f07b62,1,credit_card,4,441.16
103885,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,66dea50a8b16d9b4dee7af250b4be1a5,1,debit_card,1,86.86

## Extracción de datos desde las tablas customers y geolocations

Incidencia BBT2-20

In [14]:
# Crear un DataFrame que contenga el JOIN de la tabla customers y tabla geolocation.
customers_and_geolocation = pd.read_sql_query('''
SELECT customer_unique_id, customer_zip_code_prefix as Zip_code, AVG(geolocation_lat) as Latitud, AVG(geolocation_lng) as Longitud
FROM customers c
JOIN geolocation g
ON g.geolocation_zip_code_prefix = c.customer_zip_code_prefix
GROUP BY customer_unique_id
LIMIT 100

''', conn)

#Código anterior
# SELECT distinct * FROM customers c
# INNER JOIN geolocation g
# ON c.customer_zip_code_prefix = g.geolocation_zip_code_prefix
# LIMIT 1000

In [15]:
customers_and_geolocation

                  customer_unique_id  Zip_code    Latitud   Longitud
0   0000366f3b9a7992bf8c76cfdf3221e2      7787 -23.340235 -46.830140
1   0000b849f77a49e4a4ce2b2a4ca5be3f      6053 -23.559115 -46.787626
2   0000f46a3911fa3c0805444483337064     88115 -27.542880 -48.633426
3   0000f6ccb0745a6a4b88665a16c9f078     66812  -1.312214 -48.483159
4   0004aac84e0df4da2b147fca70cf8255     18040 -23.505548 -47.469705
..                               ...       ...        ...        ...
95  003c2067070f5b3d923235b1ea1cc17b     63575  -6.583339 -40.138874
96  003c457932a554e4df13834237b1ed00     18030 -23.510539 -47.459670
97  003d56767e53e08671de00da3fba8d40     37505 -22.419785 -45.467526
98  003db7adfcdc49857b095a50191b6c9d      8615 -23.547817 -46.295624
99  003e28cb6fab8a0901bff9229612375f     82560 -25.385985 -49.244509

[100 rows x 4 columns]

## Extracción de datos desde las tablas orders y geolocations

Incidencia BBT2-21

In [16]:
# Crear un DataFrame que contenga el JOIN de la tabla orders y tabla geolocation (necesita customers)

orders_and_geolocation = pd.read_sql_query('''
SELECT o.order_id, o.customer_id, AVG(g.geolocation_lat) as Latitud, AVG(g.geolocation_lng) as Longitud
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN geolocation g ON g.geolocation_zip_code_prefix = c.customer_zip_code_prefix
GROUP BY o.order_id
LIMIT 100
''', conn)

In [17]:
orders_and_geolocation

,order_id,customer_id,Latitud,Longitud
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,-21.762775,-41.309633
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,-20.220527,-50.903424
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,-19.870305,-44.593326
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,-23.089925,-46.611654
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,-23.243402,-46.827614
...,...,...,...,...
95,003a94f778ef8cfd50247c8c1b582257,da108bc410acffb1400cf9caea65a332,-20.483662,-54.665991
96,003cc6161d7a2593f2525cce0c330d32,7d9802889236ab8fc541bfb438978cd7,-23.500841,-46.678336
97,003d0634280ff3d1d3a54459349a6899,cca819156e50623e9d3762ebeee308dc,-23.491277,-46.825905
98,003d804eef0e1b856881cd18e0cc0d4c,1c1bfb2cd4aa789067295941c42120ff,-5.519211,-47.461428
99,003d9fc84ad902adf2265248b5ffe1a4,8c66482ec333eae596c93a9131981a9a,-23.587635,-46.749336

## Filtrar datos, reducir volumen de order y payments

Incidencia BBT2-29

In [38]:
#Filtrar el DataFrame de órdenes y pagos para resguardar los 3 pagos de mayor importe por cliente.
#No es eficiente la consulta en SQL, POR LO QUE LO PUDE HACER EN PANDAS
#DataFrame ordenado por 'customer_id' y 'payment_value'
df_ordenado = orders_and_payments.sort_values(by=['customer_id', 'payment_value'], ascending=[True, False])

#Groupby y head para tomar las primeras 3 filas de cada cliente
top_3_payments = df_ordenado.groupby('customer_id').head(3).reset_index(drop=True)

In [39]:
top_3_payments

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,5f79b5b0931d63f1a42989eb65b9da6e,00012a2ce6f8dcda20d059ce98491703,delivered,2017-11-14 16:08:26,2017-11-14 16:35:32,2017-11-17 15:32:08,2017-11-28 15:41:30,2017-12-04 00:00:00,5f79b5b0931d63f1a42989eb65b9da6e,1,credit_card,8,114.74
1,a44895d095d7e0702b6a162fa2dbeced,000161a058600d5901f007fab4c27140,delivered,2017-07-16 09:40:32,2017-07-16 09:55:12,2017-07-19 19:09:37,2017-07-25 18:57:33,2017-08-04 00:00:00,a44895d095d7e0702b6a162fa2dbeced,1,credit_card,5,67.41
2,316a104623542e4d75189bb372bc5f8d,0001fd6190edaaf884bcaf3d49edf079,delivered,2017-02-28 11:06:43,2017-02-28 11:15:20,2017-03-01 15:24:20,2017-03-06 08:57:49,2017-03-22 00:00:00,316a104623542e4d75189bb372bc5f8d,1,credit_card,10,195.42
3,5825ce2e88d5346438686b0bba99e5ee,0002414f95344307404f0ace7a26f1d5,delivered,2017-08-16 13:09:20,2017-08-17 03:10:27,2017-08-19 11:34:29,2017-09-13 20:06:02,2017-09-14 00:00:00,5825ce2e88d5346438686b0bba99e5ee,1,boleto,1,179.35
4,0ab7fb08086d4af9141453c91878ed7a,000379cdec625522490c315e70c7a9fb,delivered,2018-04-02 13:42:17,2018-04-04 03:10:19,2018-04-04 18:11:09,2018-04-13 20:21:08,2018-04-18 00:00:00,0ab7fb08086d4af9141453c91878ed7a,1,boleto,1,107.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102975,814d6a3a7c0b32b2ad929ac6328124e9,fffecc9f79fd8c764f843e9951b11341,delivered,2018-03-29 16:59:26,2018-03-29 17:10:27,2018-03-31 14:29:38,2018-04-10 17:20:49,2018-04-27 00:00:00,814d6a3a7c0b32b2ad929ac6328124e9,1,credit_card,1,0.64
102976,8c855550908247a7eff50281b92167a8,fffeda5b6d849fbd39689bb92087f431,delivered,2018-05-22 13:36:02,2018-05-22 13:54:37,2018-05-25 13:25:00,2018-06-08 18:03:31,2018-06-29 00:00:00,8c855550908247a7eff50281b92167a8,1,credit_card,3,63.13
102977,83b5fc912b2862c5046555ded1483ae9,ffff42319e9b2d713724ae527742af25,delivered,2018-06-13 16:57:05,2018-06-13 17:20:23,2018-06-15 18:52:00,2018-06-18 18:33:05,2018-06-25 00:00:00,83b5fc912b2862c5046555ded1483ae9,1,credit_card,2,214.13
102978,d0e7be325a1c986babc4e1cdb91edc03,ffffa3172527f765de70084a7e53aae8,delivered,2017-09-02 11:53:32,2017-09-02 12:05:40,2017-09-08 20:04:11,2017-09-14 19:47:40,2017-09-26 00:00:00,d0e7be325a1c986babc4e1cdb91edc03,1,credit_card,4,45.50
102979,2e935fa1d39497aa0ec3f1107fbfb5b8,ffffe8b65bbe3087b653a978c870db99,unavailable,2017-09-29 14:07:03,2017-10-03 06:34:13,None,None,2017-10-24 00:00:00,2e935fa1d39497aa0ec3f1107fbfb5b8,1,boleto,1,18.37

## Filtrar datos, reducir volumen de orders y reviews

Incidencia BBT2-32

In [23]:
#Filtrar el DataFrame de órdenes para resguardar las revisiones con puntaje mayor o igual a 3 y mayor importe de la órden.

#Unimos df de orders con df order_reviews con merge
orders_and_reviews = pd.merge(ecommerce_orders, ecommerce_order_reviews, on='order_id')

#Unimos orders_and_reviews con order_payments con merge
orders_reviews_payments = pd.merge(orders_and_reviews, ecommerce_order_payments, on='order_id')

#Filtramos
df_result = orders_reviews_payments[
    (orders_reviews_payments['review_score'] >= 3)
].sort_values(by='payment_value', ascending=False)

In [24]:
df_result

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,payment_sequential,payment_type,payment_installments,payment_value
23124,0812eb902a67711a1cb742b3cdaa65ae,c6e2731c5b391845f6800c97401a43a9,delivered,2017-02-12 20:37:36,2017-02-12 20:45:12,2017-02-16 09:23:13,2017-03-03 14:23:18,2017-03-09 00:00:00,e2fbd9f0ef7b724c7ecb351601a857e7,5,NaN,"Mesmo a máquina ter vindo errada, já se pronti...",2017-03-04 00:00:00,2017-03-04 21:40:41,1,credit_card,8,6929.31
3664,f5136e38d1a14a4dbd87dff67da82701,3fd6777bbce08a352fddd04e4a7cc8f6,delivered,2017-05-24 18:14:34,2017-05-26 02:45:17,2017-05-26 11:20:47,2017-06-05 17:09:48,2017-06-28 00:00:00,1b73e6c7cd135008ebeb18404b776ddc,5,NaN,NaN,2017-06-06 00:00:00,2017-06-07 19:35:23,1,boleto,1,6726.66
55639,a96610ab360d42a2e5335a3998b4718a,df55c14d1476a9a3467f131269c2477f,delivered,2017-04-01 15:58:40,2017-04-03 13:25:18,2017-04-11 15:10:34,2017-04-17 11:04:45,2017-05-02 00:00:00,52632252782892317727260a87bc0663,5,NaN,NaN,2017-04-18 00:00:00,2017-04-21 15:17:33,1,credit_card,10,4950.34
42112,199af31afc78c699f0dbf71fb178d4d4,24bbf5fd2f2e1b359ee7de94defc4a15,delivered,2017-04-18 18:50:13,2017-04-19 15:50:15,2017-04-25 13:39:59,2017-05-07 10:42:39,2017-05-15 00:00:00,dbf39e1ecc23738d2e7b56875fb49fac,4,NaN,NaN,2017-05-08 00:00:00,2017-05-09 02:00:10,1,credit_card,8,4764.34
42128,8dbc85d1447242f3b127dda390d56e19,3d979689f636322c62418b6346b1c6d2,delivered,2018-06-22 12:23:19,2018-06-22 12:36:36,2018-06-22 13:00:00,2018-07-06 01:08:30,2018-07-17 00:00:00,5740810e4d16fe8fc6a1b959558f63a5,5,Satisfeito,Cumpriu o prometido,2018-07-06 00:00:00,2018-07-06 21:30:22,1,credit_card,8,4681.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74689,0218c7a4fb8d5b1bd22c82b783b8359c,430ec51e3c42def76f0d79a8edb21784,delivered,2017-10-13 12:58:35,2017-10-13 13:09:23,2017-10-13 19:33:52,2017-10-23 12:12:29,2017-10-31 00:00:00,9f82e3e85b0eef3488d8717954309d15,5,NaN,"Entrega dentro do prazo, embalagem/produto bem...",2017-10-24 00:00:00,2017-10-24 18:33:54,1,credit_card,1,0.01
89430,b23878b3e8eb4d25a158f57d96331b18,648121b599d98c420ef93f6135f8c80c,delivered,2017-05-27 19:20:24,2017-05-27 19:35:17,2017-05-29 04:49:37,2017-06-07 08:53:10,2017-06-29 00:00:00,f75bfd523e8001ea6c62f86c48fae8a9,5,NaN,NaN,2017-06-08 00:00:00,2017-06-10 19:28:35,4,voucher,1,0.00
41690,4637ca194b6387e2d538dc89b124b0ee,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaN,NaN,NaN,2018-09-10 00:00:00,9efef4d70190c1bdb9b12872cc8144fc,3,Produto Avariado,Recebi o Diario do Bebê c um pequeno rasgo na ...,2018-08-17 00:00:00,2018-08-18 15:32:40,1,not_defined,1,0.00
101085,8bcbe01d44d147f901cd3192671144db,f2def7f64f36952f2f5a9791f0285f34,delivered,2018-01-24 23:24:14,2018-01-24 23:37:20,2018-01-30 22:43:30,2018-02-02 21:26:42,2018-02-21 00:00:00,3d42038fd2a7d35a88b93cb3e51796a3,4,NaN,NaN,2018-02-03 00:00:00,2018-02-11 17:34:29,4,voucher,1,0.00
33736,6ccb433e00daae1283ccc956189c82ae,843b211abe7b0264dd4a69eafc5bdf43,delivered,2017-10-26 23:51:35,2017-10-27 00:46:58,2017-10-27 19:53:03,2017-11-08 18:47:00,2017-11-22 00:00:00,8d0e1d286cc6f63e3a784779c9d1f7d8,4,NaN,NaN,2017-11-09 00:00:00,2018-02-14 13:57:57,4,voucher,1,0.00