### Clonar repositorio

In [ ]:
! git clone https://github.com/alkemyTech/BBVA-BDS-W1-T2.git

fatal: destination path 'BBVA-BDS-W1-T2' already exists and is not an empty directory.

## Crear una Base de datos

In [ ]:
import sqlite3 as sql

In [ ]:
#conecta a la base de datos
conn = sql.connect('ecommercer.db')
cursor = conn.cursor()

importamos pandas

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

Cargar csv

In [ ]:
ecommerce_customers = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_customers_dataset.csv')
ecommerce_geolocation =pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_geolocation_dataset.csv')
ecommerce_orders = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_orders_dataset.csv')
ecommerce_order_items = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_items_dataset.csv')
ecommerce_products = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_products_dataset.csv')
ecommerce_order_payments = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_payments_dataset.csv')
ecommerce_order_reviews = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_order_reviews_dataset.csv')
product_category_name_translation = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de product_category_name_translation.csv')
ecommerce_sellers = pd.read_csv('/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_sellers_dataset.csv')

Guardar los DataFrames en la base de datos como tablas

In [ ]:
ecommerce_customers.to_sql('products', conn, index=True, if_exists='replace')
ecommerce_order_items.to_sql('order_items', conn, if_exists='replace', index=False)
ecommerce_order_payments.to_sql('order_payments', conn, if_exists='replace', index=False)
ecommerce_orders.to_sql('orders', conn, if_exists='replace', index=False)
ecommerce_products.to_sql('products', conn, if_exists='replace', index=False)
ecommerce_geolocation.to_sql('geolocation', conn, if_exists='replace', index=False)
ecommerce_order_reviews.to_sql('reviews', conn, if_exists='replace', index=False)
product_category_name_translation.to_sql('product_category_name_translation', conn, if_exists='replace', index=False)
ecommerce_sellers.to_sql('sellers', conn, if_exists='replace', index=False)

3095

cargar archivo excel

In [ ]:
excel_file='/content/BBVA-BDS-W1-T2/datasets/Copia de ecommerce_geolocation_dataset.xlsx'

Cargar el archivo Excel en un DataFrame

In [ ]:
df_excel = pd.read_excel(excel_file, engine='openpyxl')

Extraccion de datos desde la tabla orders_items y sellers

In [ ]:
query = '''
SELECT oi.*, s.*
FROM order_items oi
JOIN sellers s ON oi.seller_id = s.seller_id
'''
orders_seller_df = pd.read_sql_query(query, conn)
orders_seller_df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,48436dade18ac8b2bce089ec2a041202,27277,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,dd7ddc04e1b6c2c614352b383efe2d36,3471,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,5b51032eddd242adc84c38acab88f23d,37564,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,9d7a1d34a5052409006425275ba1c2b4,14403,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,df560393f3a51e74553ab94004ba5c87,87900,loanda,PR
...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b8bc237ba3788b23da09c0f1f3a3288c,88303,itajai,SC
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,f3c38ab652836d21de61fb8314b69182,1206,sao paulo,SP
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,c3cfdc648177fdbbbb35635a37472c53,80610,curitiba,PR
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,2b3e4a2a3ea8e01938cabda2a3e5cc79,4733,sao paulo,SP
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,f7ccf836d21b2fb1de37564105216cc1,14940,ibitinga,SP

Extracción de datos desde las tablas orders_items, products y products_category_translation

In [ ]:
query_2 = '''
SELECT oi.*, p.product_category_name
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
INNER JOIN product_category_name_translation t ON p.product_category_name = t.product_category_name
'''

product_category_name = pd.read_sql_query(query_2, conn)
product_category_name

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim
...,...,...,...,...,...,...,...,...
111018,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,utilidades_domesticas
111019,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,informatica_acessorios
111020,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,esporte_lazer
111021,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,informatica_acessorios
111022,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,cama_mesa_banho

Extracción de datos desde las tablas orders y reviews

In [ ]:
query_3 = """
SELECT o.*, r.review_score
FROM orders o
INNER JOIN reviews r ON o.order_id = r.order_id
"""
orders_reviews_df = pd.read_sql_query(query_3, conn)
orders_reviews_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,4
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,4
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,5
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,5
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,5
...,...,...,...,...,...,...,...,...,...
99219,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,5
99220,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,4
99221,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,5
99222,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2
99223,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,5